### ISSUE TITLE
When creating an event my app crashed

### ISSUE THREAD

**Issue by Sherali5543** [CMPUT301F24napkin/napkinfactory#145]
Entered name, entrant limit of 1, event date set to today, lottery date set to today, image uploaded, geolocation enabled, description entered. Clicked created, resolved error with event date being today (this is already mentioned in another issue). Set event date to tomorrow, clicked create, app stalled before showing me my events and crashing

FATAL EXCEPTION: main
                                                                                                    Process: com.example.napkinapp, PID: 7224
                                                                                                    java.lang.IllegalStateException: Fragment CreateEventFragment{c97b1e9} (c3cfdd17-71d9-42d8-bf36-00e0e82bd1c3) not associated with a fragment manager.
                                                                                                    	at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1117)
                                                                                                    	at com.example.napkinapp.fragments.createevent.CreateEventFragment$2$2.onSuccess(CreateEventFragment.java:365)
                                                                                                    	at com.example.napkinapp.fragments.createevent.CreateEventFragment$2$2.onSuccess(CreateEventFragment.java:362)
                                                                                                    	at com.example.napkinapp.utils.DB_Client.lambda$updateAll$8(DB_Client.java:294)
                                                                                                    	at com.example.napkinapp.utils.DB_Client$$ExternalSyntheticLambda12.onComplete(D8$$SyntheticClass:0)
                                                                                                    	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by Sherali5543** [comment]
I now have duplicate events
